# Generated by Django 3.2.5 on 2021-07-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='payment_id',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='coffee',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
